
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# --- PS2 SDK paths ---
set(PS2DEV $ENV{PS2DEV})
set(PS2SDK $ENV{PS2SDK})
set(GSKIT  ${PS2DEV}/gsKit)

# --- SDL2 from ps2sdk ports ---
set(PS2PORTS ${PS2SDK}/ports)

# --- Sources (sama dengan CMakeLists.txt utama, minus GL/WebGL) ---
set(TH06_GAME_SOURCES
    ${TH06_ROOT}/src/main.cpp
    ${TH06_ROOT}/src/GLFunc.cpp
    ${TH06_ROOT}/src/AnmManager.cpp
    ${TH06_ROOT}/src/AsciiManager.cpp
    ${TH06_ROOT}/src/BombData.cpp
    ${TH06_ROOT}/src/BulletData.cpp
    ${TH06_ROOT}/src/BulletManager.cpp
    ${TH06_ROOT}/src/Chain.cpp
    ${TH06_ROOT}/src/Controller.cpp
    ${TH06_ROOT}/src/EclManager.cpp
    ${TH06_ROOT}/src/EffectManager.cpp
    ${TH06_ROOT}/src/Ending.cpp
    ${TH06_ROOT}/src/EnemyEclInstr.cpp
    ${TH06_ROOT}/src/EnemyManager.cpp
    ${TH06_ROOT}/src/FileSystem.cpp
    ${TH06_ROOT}/src/GameErrorContext.cpp
    ${TH06_ROOT}/src/GameManager.cpp
    ${TH06_ROOT}/src/GamePaths.cpp
    ${TH06_ROOT}/src/GameWindow.cpp
    ${TH06_ROOT}/src/Gui.cpp
    ${TH06_ROOT}/src/ItemManager.cpp
    ${TH06_ROOT}/src/MainMenu.cpp
    ${TH06_ROOT}/src/MidiOutput.cpp
    ${TH06_ROOT}/src/MusicRoom.cpp
    ${TH06_ROOT}/src/Player.cpp
    ${TH06_ROOT}/src/ReplayManager.cpp
    ${TH06_ROOT}/src/ResultScreen.cpp
    ${TH06_ROOT}/src/Rng.cpp
    ${TH06_ROOT}/src/ScreenEffect.cpp
    ${TH06_ROOT}/src/SoundPlayer.cpp
    ${TH06_ROOT}/src/Stage.cpp
    ${TH06_ROOT}/src/Supervisor.cpp
    ${TH06_ROOT}/src/TextHelper.cpp
    ${TH06_ROOT}/src/utils.cpp
    ${TH06_ROOT}/src/ZunTimer.cpp
    ${TH06_ROOT}/src/midi/MidiDefault.cpp
    ${TH06_ROOT}/src/graphics/FixedFunctionGL.cpp
    ${TH06_ROOT}/src/graphics/WebGL.cpp
    ${TH06_ROOT}/src/graphics/GsKitStub.cpp
    ${TH06_ROOT}/src/pbg3/FileAbstraction.cpp
    ${TH06_ROOT}/src/pbg3/IPbg3Parser.cpp
    ${TH06_ROOT}/src/pbg3/Pbg3Archive.cpp
    ${TH06_ROOT}/src/pbg3/Pbg3Parser.cpp
    # PS2 platform layer
    ${TH06_ROOT}/src/platform/ps2/PS2Platform.cpp
    ${TH06_ROOT}/src/platform/ps2/PS2Main.cpp
)

add_executable(th06.elf ${TH06_GAME_SOURCES})

# --- i18n codegen ---
find_program(TH06_PYTHON NAMES python3 python REQUIRED)
set(I18N_TPL "${TH06_ROOT}/src/i18n.tpl")
set(I18N_HPP "${TH06_ROOT}/build/autogenerated/i18n.hpp")

add_custom_command(
    OUTPUT "${I18N_HPP}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${TH06_ROOT}/build/autogenerated"
    COMMAND ${TH06_PYTHON} "${TH06_ROOT}/scripts/gen_i18n.py"
        "${I18N_TPL}" "${I18N_HPP}" "utf-8"
    DEPENDS "${I18N_TPL}" "${TH06_ROOT}/scripts/gen_i18n.py"
)
add_custom_target(generate_i18n DEPENDS "${I18N_HPP}")
add_dependencies(th06.elf generate_i18n)

# --- Compile flags ---
target_compile_options(th06.elf PRIVATE
    -g0
    -mno-gpopt
    -fpermissive
    -Wno-unknown-pragmas
    -Wno-changes-meaning
    # -DNO_VU0_VECTORS
    -DNO_ASM
)

target_compile_definitions(th06.elf PRIVATE
    __PS2__
    PS2
    _EE
    _MIPSEL
    TH06_USE_GLES=1
)

# --- Include dirs ---
target_include_directories(th06.elf PRIVATE
    ${TH06_ROOT}/src
    ${TH06_ROOT}/build/autogenerated
    ${TH06_ROOT}/3rdparty/rapidjson/include
    ${PS2SDK}/ee/include
    ${PS2SDK}/common/include
    ${PS2PORTS}/include
    ${PS2PORTS}/include/SDL2
    ${GSKIT}/include
)

# --- Link libraries ---
target_link_directories(th06.elf PRIVATE
    ${PS2SDK}/ee/lib
    ${PS2PORTS}/lib
    ${GSKIT}/lib
)

target_link_libraries(th06.elf PRIVATE
    SDL2
    SDL2_mixer
    SDL2_image
    SDL2_ttf
    ps2glut
    ps2gl
    ps2stuff
    dma
    gskit
    gskit_toolkit
    dmakit
    ps2_drivers
    ${PS2SDK}/ee/lib/libdebug.a
    sior
    patches
    audsrv
    pad
    mtap
    kernel
    png
    z
    freetype
    cglue
    stdc++
    m
)

# --- ELF linker script ---
target_link_options(th06.elf PRIVATE
    
    -Wl,-zmax-page-size=128
    -Wl,-Map,out.map
)